### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for long org.opencv.wechat_qrcode.WeChatQRCode.WeChatQRCode_0

### ISSUE THREAD

**Issue by BraveMomo** [woshiwzy/opencv_wechat_qr#2]
![03$IZ(H_$Y2{B)U{K7{L~8W](https://user-images.githubusercontent.com/22335503/112279692-29088b00-8cbf-11eb-9020-481ff8c85b38.png)

**Comment by BraveMomo** [comment]
求助

**Comment by BraveMomo** [comment]
大佬能把编译过程列出来吗，我自己搞，我这边设备比较杂

**Comment by woshiwzy** [comment]
> 大佬能把编译过程列出来吗，我自己搞，我这边设备比较杂

文章链接 https://blog.csdn.net/wang382758656/article/details/114762661

**Comment by BraveMomo** [comment]
> > 大佬能把编译过程列出来吗，我自己搞，我这边设备比较杂
> 
> 文章链接 https://blog.csdn.net/wang382758656/article/details/114762661

Mac电脑……那我这没有啊，大佬能更新一下新的so吗

**Comment by woshiwzy** [comment]
> > > 大佬能把编译过程列出来吗，我自己搞，我这边设备比较杂
> > 
> > 
> > 文章链接 https://blog.csdn.net/wang382758656/article/details/114762661
> 
> Mac电脑……那我这没有啊，大佬能更新一下新的so吗

我晚上回去编一波，编一次要好久....

**Comment by BraveMomo** [comment]
> > > > 大佬能把编译过程列出来吗，我自己搞，我这边设备比较杂
> > > 
> > > 
> > > 文章链接 https://blog.csdn.net/wang382758656/article/details/114762661
> > 
> > 
> > Mac电脑……那我这没有啊，大佬能更新一下新的so吗
> 
> 我晚上回去编一波，编一次要好久....

辛苦了，万分感谢，最好有各种arm架构的，这样兼容性应该会更好，比如armeabi，这个好像可以最低兼容

**Comment by woshiwzy** [comment]
> > > > > 大佬能把编译过程列出来吗，我自己搞，我这边设备比较杂
> > > > 
> > > > 
> > > > 文章链接 https://blog.csdn.net/wang382758656/article/details/114762661
> > > 
> > > 
> > > Mac电脑……那我这没有啊，大佬能更新一下新的so吗
> > 
> > 
> > 我晚上回去编一波，编一次要好久....
> 
> 辛苦了，万分感谢，最好有各种arm架构的，这样兼容性应该会更好，比如armeabi，这个好像可以最低兼容

最新的so已经上传了

**Comment by woshiwzy** [comment]
> > > > > > 大佬能把编译过程列出来吗，我自己搞，我这边设备比较杂
> > > > > 
> > > > > 
> > > > > 文章链接 https://blog.csdn.net/wang382758656/article/details/114762661
> > > > 
> > > > 
> > > > Mac电脑……那我这没有啊，大佬能更新一下新的so吗
> > > 
> > > 
> > > 我晚上回去编一波，编一次要好久....
> > 
> > 
> > 辛苦了，万分感谢，最好有各种arm架构的，这样兼容性应该会更好，比如armeabi，这个好像可以最低兼容
> 
> 最新的so已经上传了

cmake 都不支持armeabi了
