### ISSUE TITLE
编译二维码问题

### ISSUE THREAD

**Issue by DyncKathline** [woshiwzy/opencv_wechat_qr#3]
我这边根据教程https://blog.csdn.net/poorkick/article/details/113665108编译出来了，但是并没有wechat_qrcode的，请问这部分怎么做的，另外是不是可以加入二维码这部分，其他可以不编译进去
![image](https://user-images.githubusercontent.com/16282974/112470270-6e9f8380-8da5-11eb-96cd-35f304f1b82f.png)

**Comment by woshiwzy** [comment]
你编译的时候 OPENCV_EXTRA_MODULES_PATH 这个参数应该没有值或者没填上值（可能是cmake bug，我也栽了几次坑），make之前检查一下这个参数，有这个参数也要看参数有没有值，确保这个参数存在且有值。

        关于你标红的部分，如果OPENCV_EXTRA_MODULES_PATH 参数没有起作用，就没有这些包，需要的c++部分也就没有编译到so中，即便你把java代码拷贝进去，so的c++函数不全，运行时会报错。

**Comment by DyncKathline** [comment]
> ```
>      你编译的时候 OPENCV_EXTRA_MODULES_PATH 这个参数应该没有值或者没填上值（可能是cmake bug，我也栽了几次坑），make之前检查一下这个参数，有这个参数也要看参数有没有值，确保这个参数存在且有值。
> 
>     关于你标红的部分，如果OPENCV_EXTRA_MODULES_PATH 参数没有起作用，就没有这些包，需要的c++部分也就没有编译到so中，即便你把java代码拷贝进去，so的c++函数不全，运行时会报错。
> ```

加了好像也没用，继续编译，是要删掉build文件，重新来一遍吗，另外我上面说的，能只加入wechat_qrcode，其他opencv不需要。

**Comment by woshiwzy** [comment]
> > ```
> >      你编译的时候 OPENCV_EXTRA_MODULES_PATH 这个参数应该没有值或者没填上值（可能是cmake bug，我也栽了几次坑），make之前检查一下这个参数，有这个参数也要看参数有没有值，确保这个参数存在且有值。
> > 
> >     关于你标红的部分，如果OPENCV_EXTRA_MODULES_PATH 参数没有起作用，就没有这些包，需要的c++部分也就没有编译到so中，即便你把java代码拷贝进去，so的c++函数不全，运行时会报错。
> > ```
> 
> 加了好像也没用，继续编译，是要删掉build文件，重新来一遍吗，另外我上面说的，能只加入wechat_qrcode，其他opencv不需要。

删了build目录重来一次吧，make之前一定检查一下参数，有些模块理论上不需要，但是qr模块还是有很多依赖，你要是不完全清楚而干掉其他模块之后，可能编不出so来，这几天在研究为啥，还没弄清楚，当然你也可以只编译你需要的核心模块，这个有点难度....
