### ISSUE TITLE
导入编译报错，这是什么原因，是和我本地环境有关吗？

### ISSUE THREAD

**Issue by ziyouxiaozi** [woshiwzy/opencv_wechat_qr#5]
如果是因为我本地环境的问题，能发一下你那边的环境给我看看吗？
![8(IS76IS_Q_`_V@$TW32}Y5](https://user-images.githubusercontent.com/2511739/116054850-b2402280-a6ae-11eb-9fae-2f8b72b77c12.png)

**Comment by leolbyy** [comment]
我也有这个报错
请问你是怎么解决的啊

**Comment by ziyouxiaozi** [comment]
我也没有解决

**Comment by ziyouxiaozi** [comment]
> 我也有这个报错
> 请问你是怎么解决的啊

我也没有解决
